- block:
  - import_tasks: groups/assert.yml
  - import_tasks: groups/group.yml

  - name: include_tasks > loop over host_vars users/*.yml files
    include_tasks: users/loop.yml
    # with_fileglob: "{{ inventory_dir }}/host_vars/{{ ansible_hostname }}/users/*.yml"
    with_fileglob: "{{ users_inventory_path }}"

  # - include_tasks: users.yml
  #   loop: "{{ user }}"
  #   loop_control:
  #     loop_var: i_user

  tags: users
