- block:
  - import_tasks: assert.yml

  - import_tasks: groups.yml

  - include_tasks: user_accounts.yml
    loop: "{{ user }}"
    loop_control:
      loop_var: i_user

  - import_tasks: user_dirs.yml

  tags: users
