- block:
  - name: ({{ i_user.name }}) file > create user directories
    file:
      path:  "{{ ('/root' if item.0.owner == 'root' else ('/home/' + item.0.owner)) + '/' + item.1 }}"
      owner: "{{ item.0.owner }}"
      state: directory
    with_subelements:
      - "{{ user_dirs }}"
      - list
      - skip_missing: true

  tags: user_dirs
