- block:
  - name: ({{ _user.name }}) assert > system uid between 100 to 499
    assert:
      that:
        - _user.uid >= 100
        - _user.uid <= 499
    when:
      - _user.uid    is defined
      - _user.system is defined
      - _user.system is true

  - name: ({{ _user.name }}) assert > non system uid between 1000 to 60000
    assert:
      that:
        - _user.uid >= 1000
        - _user.uid <= 60000
    when:
      - _user.uid is defined
      - (_user.system is not defined) or (not _user.system)

  tags: users_assert
