- block:
  - name: include_vars > user files
    include_vars:
      file: "{{ item }}"
      name: "include"

  - name: set_fact > _user var
    set_fact:
      _user: "{{ user_default | combine(include.user, recursive=true) }}"

  - import_tasks: assert.yml

  - import_tasks: user.yml

  tags: users, user_accounts
